version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/educacion-adaptativa
      - JWT_SECRET=jwt_secret_for_development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 